# Generated by Django 5.0.6 on 2024-06-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userinfo_genero"),
        ("gifts", "0002_gift_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="likes",
            field=models.ManyToManyField(to="accounts.userinfo"),
        ),
    ]
