# Generated by Django 5.0.6 on 2024-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userinfo_genero"),
        ("gifts", "0003_gift_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="likes",
            field=models.ManyToManyField(blank=True, to="accounts.userinfo"),
        ),
    ]
