# Generated by Django 5.0.6 on 2024-06-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0005_gift_cat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gift",
            name="likes",
        ),
    ]
