# Generated by Django 5.0.6 on 2024-06-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userinfo_style"),
        ("gifts", "0006_remove_gift_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="likes",
            field=models.ManyToManyField(blank=True, to="gifts.gift"),
        ),
    ]
